#!/usr/bin/env python3
"""
Detection Pipeline Visualization

Visualization script that reads JSON files generated by rex_play.py
and creates comparison visualization frames.

Usage:
    python rex_play_vis.py --output-dir output

The script auto-detects JSON files from the output directory:
    - vocabulary_results.json
    - yolo_results.json
    - rex_omni_detection_results.json
    - rex_omni_pointing_results.json (optional)

Robin Eshraghi  12/05/2025
"""

import os
from pathlib import Path

# Check if standard temp directories exist and are writable
temp_dirs = ['/tmp', '/var/tmp', '/usr/tmp']
temp_dir_found = False

for temp_dir in temp_dirs:
    if os.path.exists(temp_dir) and os.access(temp_dir, os.W_OK):
        temp_dir_found = True
        break

if not temp_dir_found:
    user_tmp = Path.home() / '.tmp'
    user_tmp.mkdir(exist_ok=True, mode=0o700)
    os.environ['TMPDIR'] = str(user_tmp)
    os.environ['TMP'] = str(user_tmp)
    os.environ['TEMP'] = str(user_tmp)

import sys

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = SCRIPT_DIR.parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import argparse
import json
import logging
from typing import Any, Dict, List, Optional

import cv2
import numpy as np

from tiamat_agent.vision_grounding.obs_data_buffer import ObsDataEntry
# Import shared utilities from processing script to avoid duplication
from tiamat_agent.vision_grounding.rex_play import (
    CAMERA_ROTATIONS,
    rotate_images_for_cameras,
    load_json,
    load_captured_buffer,
    get_all_vocabulary,
)

# ============================================================================
# Configuration
# ============================================================================

DEFAULT_OUTPUT_DIR = SCRIPT_DIR / "output"
DEFAULT_FRAME_DIR = DEFAULT_OUTPUT_DIR / "detection_frame"

# Camera order for visualization
CAMERA_ORDER = ["left_rgb", "head_rgb_left", "head_rgb_right", "right_rgb", "rear_rgb"]

# Image size for grid (resize all to this)
GRID_IMAGE_SIZE = (640, 480)  # (width, height)
INFO_BOX_SIZE = (640, 480)  # (width, height)

# Detection colors
YOLO_COLOR = (0, 255, 0)  # Green
REX_OMNI_COLOR = (255, 0, 0)  # Red
POINTING_COLOR = (0, 255, 255)  # Cyan

# Constants
EMPTY_DETECTION = {"boxes": [], "labels": [], "confidences": []}
EMPTY_POINTING = {"points": [], "labels": [], "confidences": []}

logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(levelname)s - %(message)s")
logger = logging.getLogger(__name__)

# ============================================================================
# Data Loading & Adaptation
# ============================================================================
# Note: rotate_images_for_cameras, load_json, load_captured_buffer, and get_all_vocabulary
# are imported from rex_play.py to avoid duplication

def extract_detection_data(entry_data: Dict[str, Any]) -> Dict[str, Dict]:
    """Extract detections from new JSON structure.
    
    Converts: entries[entry_key]["detections"][camera_name]
    To: {camera_name: {boxes, labels, confidences}}
    """
    detections = entry_data.get("detections", {})
    result = {}
    for camera_name, camera_data in detections.items():
        result[camera_name] = {
            "boxes": camera_data.get("boxes", []),
            "labels": camera_data.get("labels", []),
            "confidences": camera_data.get("confidences", []),
        }
    return result

def extract_pointing_data(entry_data: Dict[str, Any]) -> Dict[str, Dict]:
    """Extract pointing from new JSON structure.
    
    Converts: entries[entry_key]["points"][camera_name]
    To: {camera_name: {points, labels, confidences}}
    """
    points = entry_data.get("points", {})
    result = {}
    for camera_name, camera_data in points.items():
        result[camera_name] = {
            "points": camera_data.get("points", []),
            "labels": camera_data.get("labels", []),
            "confidences": camera_data.get("confidences", []),
        }
    return result

# get_all_vocabulary is imported from rex_play.py

def auto_detect_json_files(output_dir: Path) -> Dict[str, Path]:
    """Auto-detect JSON files from output directory."""
    json_files = {
        "vocab": output_dir / "vocabulary_results.json",
        "yolo": output_dir / "yolo_results.json",
        "rex_detection": output_dir / "rex_omni_detection_results.json",
        "rex_pointing": output_dir / "rex_omni_pointing_results.json",
    }
    
    detected = {}
    for key, path in json_files.items():
        if path.exists():
            detected[key] = path
            logger.info("Found %s: %s", key, path)
        else:
            logger.warning("Missing %s: %s", key, path)
    
    return detected

# ============================================================================
# Visualization Functions
# ============================================================================

def _create_missing_image_placeholder(camera_name: str) -> np.ndarray:
    """Create a placeholder image for missing camera."""
    annotated = np.zeros((GRID_IMAGE_SIZE[1], GRID_IMAGE_SIZE[0], 3), dtype=np.uint8)
    cv2.putText(
        annotated,
        f"{camera_name} (missing)",
        (10, 30),
        cv2.FONT_HERSHEY_SIMPLEX,
        0.5,
        (128, 128, 128),
        1,
    )
    return annotated

def draw_boxes_on_image(image: np.ndarray, detections: Dict, camera_name: str, method: str) -> np.ndarray:
    """Draw bounding boxes and labels on a single image."""
    annotated = np.copy(image)
    orig_h, orig_w = annotated.shape[:2]

    scale_x = GRID_IMAGE_SIZE[0] / orig_w
    scale_y = GRID_IMAGE_SIZE[1] / orig_h

    annotated = cv2.resize(annotated, GRID_IMAGE_SIZE)
    h, w = annotated.shape[:2]

    box_color = YOLO_COLOR if method == "YOLO" else REX_OMNI_COLOR
    text_bg_color = (box_color[0] // 2, box_color[1] // 2, box_color[2] // 2)
    text_color = (255, 255, 255)

    font = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = 0.6
    thickness = 2
    (text_w, text_h), baseline = cv2.getTextSize(camera_name, font, font_scale, thickness)
    cv2.rectangle(annotated, (5, 5), (text_w + 15, text_h + baseline + 15), (0, 0, 0), -1)
    cv2.putText(annotated, camera_name, (10, text_h + 10), font, font_scale, (255, 255, 255), thickness)

    boxes = detections.get("boxes", [])
    labels = detections.get("labels", [])
    confidences = detections.get("confidences", [])

    for i, box in enumerate(boxes):
        if len(box) != 4:
            continue

        x1, y1, x2, y2 = box
        x1 = int(x1 * scale_x)
        y1 = int(y1 * scale_y)
        x2 = int(x2 * scale_x)
        y2 = int(y2 * scale_y)

        x1, y1 = max(0, x1), max(0, y1)
        x2, y2 = min(w - 1, x2), min(h - 1, y2)

        if x1 >= x2 or y1 >= y2:
            continue

        cv2.rectangle(annotated, (x1, y1), (x2, y2), box_color, 2)

        label = labels[i] if i < len(labels) else "object"
        if i < len(confidences) and confidences[i] is not None:
            label += f" {confidences[i]:.2f}"

        font_scale_label = 0.4
        thickness_label = 1
        (text_w_label, text_h_label), baseline_label = cv2.getTextSize(label, font, font_scale_label, thickness_label)

        if y1 - text_h_label - baseline_label - 5 >= 0:
            label_y1 = y1 - text_h_label - baseline_label - 5
            label_y2 = y1
            text_y = y1 - baseline_label - 2
        else:
            label_y1 = y1
            label_y2 = y1 + text_h_label + baseline_label + 5
            text_y = y1 + text_h_label + 2

        label_x2 = min(x1 + text_w_label + 10, w - 1)

        cv2.rectangle(annotated, (x1, label_y1), (label_x2, label_y2), text_bg_color, -1)
        cv2.putText(annotated, label, (x1 + 3, text_y), font, font_scale_label, text_color, thickness_label)

    return annotated

def draw_points_on_image(image: np.ndarray, pointing_results: Dict, camera_name: str) -> np.ndarray:
    """Draw points and labels on a single image."""
    annotated = np.copy(image)
    orig_h, orig_w = annotated.shape[:2]

    scale_x = GRID_IMAGE_SIZE[0] / orig_w
    scale_y = GRID_IMAGE_SIZE[1] / orig_h

    annotated = cv2.resize(annotated, GRID_IMAGE_SIZE)
    h, w = annotated.shape[:2]

    point_color = POINTING_COLOR
    text_bg_color = (point_color[0] // 2, point_color[1] // 2, point_color[2] // 2)
    text_color = (255, 255, 255)

    font = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = 0.6
    thickness = 2
    (text_w, text_h), baseline = cv2.getTextSize(camera_name, font, font_scale, thickness)
    cv2.rectangle(annotated, (5, 5), (text_w + 15, text_h + baseline + 15), (0, 0, 0), -1)
    cv2.putText(annotated, camera_name, (10, text_h + 10), font, font_scale, (255, 255, 255), thickness)

    points = pointing_results.get("points", [])
    labels = pointing_results.get("labels", [])
    confidences = pointing_results.get("confidences", [])

    # Point marker settings
    point_radius = 8
    point_thickness = 3

    for i, point in enumerate(points):
        if len(point) != 2:
            continue

        x, y = point
        x = int(x * scale_x)
        y = int(y * scale_y)

        x = max(0, min(w - 1, x))
        y = max(0, min(h - 1, y))

        # Draw point as a filled circle with outline
        cv2.circle(annotated, (x, y), point_radius, (0, 0, 0), point_thickness + 1)  # Black outline
        cv2.circle(annotated, (x, y), point_radius, point_color, point_thickness)  # Colored fill

        label = labels[i] if i < len(labels) else "point"
        if i < len(confidences) and confidences[i] is not None:
            label += f" {confidences[i]:.2f}"

        font_scale_label = 0.4
        thickness_label = 1
        (text_w_label, text_h_label), baseline_label = cv2.getTextSize(label, font, font_scale_label, thickness_label)

        # Position label to the right of the point
        label_x = x + point_radius + 5
        label_y = y

        # Adjust if label goes off screen
        if label_x + text_w_label + 10 > w:
            label_x = x - text_w_label - point_radius - 5
        if label_y - text_h_label - baseline_label - 5 < 0:
            label_y = y + text_h_label + baseline_label + 5
        else:
            label_y = y - baseline_label - 2

        label_y1 = max(0, label_y - text_h_label - baseline_label - 5)
        label_y2 = min(h - 1, label_y + baseline_label + 5)
        label_x2 = min(label_x + text_w_label + 10, w - 1)

        cv2.rectangle(annotated, (label_x, label_y1), (label_x2, label_y2), text_bg_color, -1)
        cv2.putText(annotated, label, (label_x + 3, label_y), font, font_scale_label, text_color, thickness_label)

    return annotated

def create_info_box(vocabulary: List[str], detected_vocab: List[str], method: str, width: int, height: int, total_detections: int = 0) -> np.ndarray:
    """Create a simple info box summarizing detections."""
    info_image = np.ones((height, width, 3), dtype=np.uint8) * 255
    if method == "YOLO":
        method_color = YOLO_COLOR
    elif method == "Pointing":
        method_color = POINTING_COLOR
    else:
        method_color = REX_OMNI_COLOR

    font = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = 0.8
    thickness = 2
    (text_w, text_h), baseline = cv2.getTextSize(method, font, font_scale, thickness)

    header_height = text_h + baseline + 20
    cv2.rectangle(info_image, (0, 0), (width, header_height), method_color, -1)
    cv2.putText(info_image, method, (10, text_h + 10), font, font_scale, (255, 255, 255), thickness)

    y_offset = header_height + 30
    line_height = 30
    font_scale_text = 0.7
    thickness_text = 2

    total_text = f"Total Vocabulary: {len(vocabulary)}"
    cv2.putText(info_image, total_text, (10, y_offset), font, font_scale_text, (0, 0, 0), thickness_text)
    y_offset += line_height

    detected_text = f"Detected Categories: {len(detected_vocab)}"
    cv2.putText(info_image, detected_text, (10, y_offset), font, font_scale_text, (0, 0, 0), thickness_text)
    y_offset += line_height

    if method == "Pointing":
        total_detections_text = f"Total Points: {total_detections}"
    else:
        total_detections_text = f"Total Detections: {total_detections}"
    cv2.putText(info_image, total_detections_text, (10, y_offset), font, font_scale_text, (0, 0, 0), thickness_text)
    y_offset += line_height + 10

    if detected_vocab:
        cv2.putText(info_image, "Detected List:", (10, y_offset), font, font_scale_text, (0, 0, 0), thickness_text)
        y_offset += line_height

        max_chars_per_line = 35
        detected_str = ", ".join(detected_vocab)
        words = detected_str.split(", ")
        current_line = ""
        for word in words:
            if len(current_line) + len(word) + 2 <= max_chars_per_line:
                current_line += word + ", "
            else:
                if current_line:
                    cv2.putText(
                        info_image,
                        current_line.rstrip(", "),
                        (10, y_offset),
                        font,
                        font_scale_text,
                        (0, 0, 0),
                        thickness_text,
                    )
                    y_offset += line_height
                current_line = word + ", "

        if current_line:
            cv2.putText(
                info_image,
                current_line.rstrip(", "),
                (10, y_offset),
                font,
                font_scale_text,
                (0, 0, 0),
                thickness_text,
            )
    else:
        cv2.putText(
            info_image,
            "No detections",
            (10, y_offset),
            font,
            font_scale_text,
            (128, 128, 128),
            thickness_text,
        )

    return info_image

def _create_camera_report_box(
    camera_name: str,
    camera_vocab: List[str],
    yolo_labels: List[str],
    rex_labels: List[str],
    yolo_boxes_count: int,
    rex_boxes_count: int,
    width: int,
    height: int,
) -> np.ndarray:
    """Create a camera report box showing vocabulary and detections for a specific camera."""
    report_image = np.ones((height, width, 3), dtype=np.uint8) * 255
    
    font = cv2.FONT_HERSHEY_SIMPLEX
    font_scale_header = 0.6
    thickness_header = 2
    (text_w, text_h), baseline = cv2.getTextSize(camera_name, font, font_scale_header, thickness_header)
    
    header_height = text_h + baseline + 15
    cv2.rectangle(report_image, (0, 0), (width, header_height), (100, 100, 100), -1)
    cv2.putText(report_image, camera_name, (10, text_h + 10), font, font_scale_header, (255, 255, 255), thickness_header)
    
    y_offset = header_height + 20
    line_height = 22
    font_scale_text = 0.5
    thickness_text = 1
    
    # Section 1: VLM Vocabulary
    cv2.putText(report_image, "VLM Vocab:", (10, y_offset), font, font_scale_text, (0, 0, 255), thickness_text)
    y_offset += line_height
    vocab_count_text = f"  Vocab Count: {len(camera_vocab)}"
    cv2.putText(report_image, vocab_count_text, (10, y_offset), font, font_scale_text, (0, 0, 0), thickness_text)
    y_offset += line_height
    
    if camera_vocab:
        vocab_str = ", ".join(camera_vocab)
        max_chars = 65
        words = vocab_str.split(", ")
        current_line = "  "
        for word in words:
            if len(current_line) + len(word) + 2 <= max_chars:
                current_line += word + ", "
            else:
                if current_line.strip():
                    cv2.putText(report_image, current_line.rstrip(", "), (10, y_offset), font, font_scale_text, (0, 0, 0), thickness_text)
                    y_offset += line_height
                current_line = "  " + word + ", "
        if current_line.strip():
            cv2.putText(report_image, current_line.rstrip(", "), (10, y_offset), font, font_scale_text, (0, 0, 0), thickness_text)
            y_offset += line_height
    else:
        cv2.putText(report_image, "  (none)", (10, y_offset), font, font_scale_text, (128, 128, 128), thickness_text)
        y_offset += line_height
    
    y_offset += 5
    
    # Section 2: YOLO Detections
    yolo_detected = sorted(list(set(yolo_labels))) if yolo_labels else []
    cv2.putText(report_image, "YOLO Detected:", (10, y_offset), font, font_scale_text, YOLO_COLOR, thickness_text)
    y_offset += line_height
    yolo_vocab_count_text = f"  Vocab Count: {len(yolo_detected)}"
    cv2.putText(report_image, yolo_vocab_count_text, (10, y_offset), font, font_scale_text, (0, 0, 0), thickness_text)
    y_offset += line_height
    yolo_detection_count_text = f"  Detection Count: {yolo_boxes_count}"
    cv2.putText(report_image, yolo_detection_count_text, (10, y_offset), font, font_scale_text, (0, 0, 0), thickness_text)
    y_offset += line_height
    
    if yolo_detected:
        yolo_str = ", ".join(yolo_detected)
        words = yolo_str.split(", ")
        current_line = "  "
        for word in words:
            if len(current_line) + len(word) + 2 <= max_chars:
                current_line += word + ", "
            else:
                if current_line.strip():
                    cv2.putText(report_image, current_line.rstrip(", "), (10, y_offset), font, font_scale_text, (0, 0, 0), thickness_text)
                    y_offset += line_height
                current_line = "  " + word + ", "
        if current_line.strip():
            cv2.putText(report_image, current_line.rstrip(", "), (10, y_offset), font, font_scale_text, (0, 0, 0), thickness_text)
            y_offset += line_height
    else:
        cv2.putText(report_image, "  (none)", (10, y_offset), font, font_scale_text, (128, 128, 128), thickness_text)
        y_offset += line_height
    
    # YOLO Did not find
    yolo_missing = sorted(list(set(camera_vocab) - set(yolo_detected))) if camera_vocab else []
    if yolo_missing:
        y_offset += 3
        cv2.putText(report_image, "  Did not find:", (10, y_offset), font, font_scale_text, (200, 0, 0), thickness_text)
        y_offset += line_height
        yolo_missing_str = ", ".join(yolo_missing)
        words = yolo_missing_str.split(", ")
        current_line = "    "
        for word in words:
            if len(current_line) + len(word) + 2 <= max_chars:
                current_line += word + ", "
            else:
                if current_line.strip():
                    cv2.putText(report_image, current_line.rstrip(", "), (10, y_offset), font, font_scale_text, (128, 128, 128), thickness_text)
                    y_offset += line_height
                current_line = "    " + word + ", "
        if current_line.strip():
            cv2.putText(report_image, current_line.rstrip(", "), (10, y_offset), font, font_scale_text, (128, 128, 128), thickness_text)
            y_offset += line_height
    
    y_offset += 5
    
    # Section 3: Rex-Omni Detections
    rex_detected = sorted(list(set(rex_labels))) if rex_labels else []
    cv2.putText(report_image, "Rex Detected:", (10, y_offset), font, font_scale_text, REX_OMNI_COLOR, thickness_text)
    y_offset += line_height
    rex_vocab_count_text = f"  Vocab Count: {len(rex_detected)}"
    cv2.putText(report_image, rex_vocab_count_text, (10, y_offset), font, font_scale_text, (0, 0, 0), thickness_text)
    y_offset += line_height
    rex_detection_count_text = f"  Detection Count: {rex_boxes_count}"
    cv2.putText(report_image, rex_detection_count_text, (10, y_offset), font, font_scale_text, (0, 0, 0), thickness_text)
    y_offset += line_height
    
    if rex_detected:
        rex_str = ", ".join(rex_detected)
        words = rex_str.split(", ")
        current_line = "  "
        for word in words:
            if len(current_line) + len(word) + 2 <= max_chars:
                current_line += word + ", "
            else:
                if current_line.strip():
                    cv2.putText(report_image, current_line.rstrip(", "), (10, y_offset), font, font_scale_text, (0, 0, 0), thickness_text)
                    y_offset += line_height
                current_line = "  " + word + ", "
        if current_line.strip():
            cv2.putText(report_image, current_line.rstrip(", "), (10, y_offset), font, font_scale_text, (0, 0, 0), thickness_text)
            y_offset += line_height
    else:
        cv2.putText(report_image, "  (none)", (10, y_offset), font, font_scale_text, (128, 128, 128), thickness_text)
        y_offset += line_height
    
    # Rex Did not find
    rex_missing = sorted(list(set(camera_vocab) - set(rex_detected))) if camera_vocab else []
    if rex_missing:
        y_offset += 3
        cv2.putText(report_image, "  Did not find:", (10, y_offset), font, font_scale_text, (200, 0, 0), thickness_text)
        y_offset += line_height
        rex_missing_str = ", ".join(rex_missing)
        words = rex_missing_str.split(", ")
        current_line = "    "
        for word in words:
            if len(current_line) + len(word) + 2 <= max_chars:
                current_line += word + ", "
            else:
                if current_line.strip():
                    cv2.putText(report_image, current_line.rstrip(", "), (10, y_offset), font, font_scale_text, (128, 128, 128), thickness_text)
                    y_offset += line_height
                current_line = "    " + word + ", "
        if current_line.strip():
            cv2.putText(report_image, current_line.rstrip(", "), (10, y_offset), font, font_scale_text, (128, 128, 128), thickness_text)
    
    return report_image

def create_comparison_grid(
    yolo_results: Dict[str, Dict],
    rex_omni_results: Dict[str, Dict],
    images_dict: Dict[str, np.ndarray],
    vocabulary: List[str],
    camera_order: List[str],
    vocabulary_by_camera: Dict[str, List[str]],
    pointing_results: Optional[Dict[str, Dict]] = None,
) -> np.ndarray:
    """Create side-by-side comparison grid for YOLO and Rex-Omni results with camera reports.
    
    Optionally includes a 4th row for pointing visualization if pointing_results is provided.
    """
    yolo_detected_vocab = set()
    yolo_total_detections = 0
    for cam_results in yolo_results.values():
        yolo_detected_vocab.update(cam_results.get("labels", []))
        yolo_total_detections += len(cam_results.get("boxes", []))
    yolo_detected_vocab = sorted(list(yolo_detected_vocab))

    rex_omni_detected_vocab = set()
    rex_omni_total_detections = 0
    for cam_results in rex_omni_results.values():
        rex_omni_detected_vocab.update(cam_results.get("labels", []))
        rex_omni_total_detections += len(cam_results.get("boxes", []))
    rex_omni_detected_vocab = sorted(list(rex_omni_detected_vocab))

    # Row 1: YOLO images + report
    yolo_images = []
    for camera_name in camera_order:
        if camera_name in images_dict:
            annotated = draw_boxes_on_image(images_dict[camera_name], yolo_results.get(camera_name, {}), camera_name, "YOLO")
        else:
            annotated = _create_missing_image_placeholder(camera_name)
        yolo_images.append(annotated)

    yolo_info = create_info_box(vocabulary, yolo_detected_vocab, "YOLO", INFO_BOX_SIZE[0], INFO_BOX_SIZE[1], yolo_total_detections)
    yolo_images.append(yolo_info)

    # Row 2: Rex-Omni images + report
    rex_omni_images = []
    for camera_name in camera_order:
        if camera_name in images_dict:
            annotated = draw_boxes_on_image(
                images_dict[camera_name],
                rex_omni_results.get(camera_name, {}),
                camera_name,
                "Rex-Omni",
            )
        else:
            annotated = _create_missing_image_placeholder(camera_name)
        rex_omni_images.append(annotated)

    rex_omni_info = create_info_box(vocabulary, rex_omni_detected_vocab, "Rex-Omni", INFO_BOX_SIZE[0], INFO_BOX_SIZE[1], rex_omni_total_detections)
    rex_omni_images.append(rex_omni_info)

    # Row 3: Camera reports + placeholder
    camera_reports = []
    for camera_name in camera_order:
        camera_vocab = vocabulary_by_camera.get(camera_name, [])
        yolo_labels = yolo_results.get(camera_name, {}).get("labels", [])
        rex_labels = rex_omni_results.get(camera_name, {}).get("labels", [])
        yolo_boxes_count = len(yolo_results.get(camera_name, {}).get("boxes", []))
        rex_boxes_count = len(rex_omni_results.get(camera_name, {}).get("boxes", []))
        
        report_box = _create_camera_report_box(
            camera_name,
            camera_vocab,
            yolo_labels,
            rex_labels,
            yolo_boxes_count,
            rex_boxes_count,
            GRID_IMAGE_SIZE[0],
            GRID_IMAGE_SIZE[1],
        )
        camera_reports.append(report_box)
    
    # Add placeholder for 6th box in row 3
    placeholder = np.ones((GRID_IMAGE_SIZE[1], GRID_IMAGE_SIZE[0], 3), dtype=np.uint8) * 255
    camera_reports.append(placeholder)

    # Stack base rows
    rows = [np.hstack(yolo_images), np.hstack(rex_omni_images), np.hstack(camera_reports)]
    
    # Row 4: Pointing images + report (optional)
    if pointing_results is not None:
        pointing_detected_vocab = set()
        pointing_total_points = 0
        for cam_results in pointing_results.values():
            pointing_detected_vocab.update(cam_results.get("labels", []))
            pointing_total_points += len(cam_results.get("points", []))
        pointing_detected_vocab = sorted(list(pointing_detected_vocab))
        
        pointing_images = []
        for camera_name in camera_order:
            if camera_name in images_dict:
                annotated = draw_points_on_image(
                    images_dict[camera_name],
                    pointing_results.get(camera_name, {}),
                    camera_name,
                )
            else:
                annotated = _create_missing_image_placeholder(camera_name)
            pointing_images.append(annotated)
        
        pointing_info = create_info_box(
            vocabulary,
            pointing_detected_vocab,
            "Pointing",
            INFO_BOX_SIZE[0],
            INFO_BOX_SIZE[1],
            pointing_total_points,
        )
        pointing_images.append(pointing_info)
        rows.append(np.hstack(pointing_images))
    
    grid = np.vstack(rows)
    return grid

# ============================================================================
# Main Task Function
# ============================================================================

def task_visualize(args) -> None:
    """Generate comparison visualization frames from JSON files."""
    output_dir = Path(args.output_dir)
    frame_dir = Path(args.frame_dir)
    # Ensure both directories exist
    output_dir.mkdir(parents=True, exist_ok=True)
    frame_dir.mkdir(parents=True, exist_ok=True)

    logger.info("Task: visualize")
    logger.info("Output directory: %s", output_dir)
    logger.info("Frame output directory: %s", frame_dir)

    # Auto-detect JSON files
    json_files = auto_detect_json_files(output_dir)
    
    if "vocab" not in json_files:
        raise FileNotFoundError("vocabulary_results.json not found. Run vocab task first.")
    if "yolo" not in json_files:
        raise FileNotFoundError("yolo_results.json not found. Run yolo task first.")
    if "rex_detection" not in json_files:
        raise FileNotFoundError("rex_omni_detection_results.json not found. Run rex_detection task first.")

    # Load JSON files
    logger.info("Loading JSON files...")
    vocab_data = load_json(json_files["vocab"])
    yolo_data = load_json(json_files["yolo"])
    rex_data = load_json(json_files["rex_detection"])
    
    # Load pointing data if available
    pointing_data = None
    if "rex_pointing" in json_files:
        logger.info("Loading pointing data...")
        pointing_data = load_json(json_files["rex_pointing"])
    else:
        logger.info("Pointing JSON not found, skipping pointing visualization")

    # Get pickle path from vocab metadata
    pickle_path = Path(vocab_data["metadata"]["pickle_path"])
    if not pickle_path.exists():
        logger.warning("Pickle path from metadata doesn't exist: %s", pickle_path)
        # Try relative to output dir
        pickle_path = output_dir.parent / pickle_path.name
        if not pickle_path.exists():
            raise FileNotFoundError(f"Pickle file not found: {pickle_path}")

    # Load pickle file
    entries = load_captured_buffer(pickle_path)

    # Process each entry
    total = 0
    saved = 0
    for entry_id, entry in entries.items():
        entry_key = str(entry_id)
        total += 1

        # Get entry data from JSONs
        vocab_entry = vocab_data.get("entries", {}).get(entry_key)
        yolo_entry = yolo_data.get("entries", {}).get(entry_key)
        rex_entry = rex_data.get("entries", {}).get(entry_key)

        if not (vocab_entry and yolo_entry and rex_entry):
            logger.warning(
                "Missing data for entry %s (vocab=%s, yolo=%s, rex=%s), skipping",
                entry_key,
                bool(vocab_entry),
                bool(yolo_entry),
                bool(rex_entry),
            )
            continue

        # Get images from pickle entry
        images_dict = getattr(entry, "rgb_images", None)
        if not images_dict:
            logger.warning("No RGB images for entry %s, skipping", entry_key)
            continue

        # Apply camera rotations
        images_dict = rotate_images_for_cameras(images_dict)

        # Extract data from new JSON structure
        vocabulary_by_camera = vocab_entry.get("vocabulary_by_camera", {})
        vocabulary = get_all_vocabulary(vocabulary_by_camera)
        
        yolo_results = extract_detection_data(yolo_entry)
        rex_omni_results = extract_detection_data(rex_entry)
        
        # Extract pointing if available
        pointing_results = None
        if pointing_data:
            pointing_entry = pointing_data.get("entries", {}).get(entry_key)
            if pointing_entry:
                pointing_results = extract_pointing_data(pointing_entry)

        # Create comparison grid
        grid = create_comparison_grid(
            yolo_results,
            rex_omni_results,
            images_dict,
            vocabulary,
            CAMERA_ORDER,
            vocabulary_by_camera,
            pointing_results,
        )

        # Save frame
        output_path = frame_dir / f"frame_{entry_key}.jpg"
        # create_comparison_grid returns RGB; OpenCV expects BGR.
        cv2.imwrite(str(output_path), cv2.cvtColor(grid, cv2.COLOR_RGB2BGR))
        saved += 1
        logger.info("Saved comparison frame: %s", output_path)

    logger.info("=" * 60)
    logger.info("Visualization complete. Frames saved: %d (processed entries: %d)", saved, total)
    logger.info("=" * 60)

# ============================================================================
# CLI & Main
# ============================================================================

def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Detection Pipeline Visualization")
    parser.add_argument(
        "--output-dir",
        type=str,
        default=str(DEFAULT_OUTPUT_DIR),
        help=f"Base output directory where JSON files are located (default: {DEFAULT_OUTPUT_DIR})",
    )
    parser.add_argument(
        "--frame-dir",
        type=str,
        default=str(DEFAULT_FRAME_DIR),
        help=f"Directory to save visualization frames (default: {DEFAULT_FRAME_DIR})",
    )
    return parser

def main(argv=None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)

    task_visualize(args)

if __name__ == "__main__":
    main()

