import pickle
import numpy as np
import torch
import cv2
import open3d as o3d
from segment_anything import sam_model_registry, SamAutomaticMaskGenerator
import os

from src_perception.obs_data_buffer import ObsDataBuffer, compose_transforms_optimized
from src_perception.components.point_cloud import create_segmented_point_cloud

# CONFIGURATION
#=======================================================
SAM_CHECKPOINT_PATH = "models/sam_vit_l_0b3195.pth"
BUFFER_PATH = "data/test_data/sample_obs_buffer_first20img.pkl" #"data/obs_buffer.pkl"
OUTPUT_DIR = "data"
OUTPUT_FILENAME = "object_pcds.pkl"
OUTPUT_PATH = os.path.join(OUTPUT_DIR, OUTPUT_FILENAME)
#=======================================================

def main():
    """
    Main function to process observation data, generate segmented object
    point clouds using SAM, and save the results.
    """
    # 1) Initialization 
    print("Initializing script...")
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu') # gpu check
    print(f"Using device: {device}")

    # Load the observation data buffer
    print(f"Loading data buffer from: {BUFFER_PATH}")
    if not os.path.exists(BUFFER_PATH):
        print(f"Error: Data buffer not found at {BUFFER_PATH}")
        return
    with open(BUFFER_PATH, "rb") as f:
        buffer: ObsDataBuffer = pickle.load(f)
    print("Data buffer loaded successfully.")

    # Load the SAM model
    print(f"Loading SAM model from: {SAM_CHECKPOINT_PATH}")
    if not os.path.exists(SAM_CHECKPOINT_PATH):
        print(f"Error: SAM checkpoint not found at {SAM_CHECKPOINT_PATH}")
        return
    sam = sam_model_registry["vit_l"](checkpoint=SAM_CHECKPOINT_PATH)
    sam.to(device)
    mask_generator = SamAutomaticMaskGenerator(model=sam, min_mask_region_area=1000)
    print("SAM model initialized.")

    # 2) Data Processing 
    # list for saving all the final object data 
    all_objects_data = []
    
    # A mapping from RGB sensor names to their corresponding transform link names
    camera_mapping = {
        "head_rgb_left": "head_left_rgbd",
        "head_rgb_right": "head_right_rgbd",
        "left_rgb": "left_rgbd",
        "right_rgb": "right_rgbd",
        "rear_rgb": "rear_rgbd"
    }

    # Initialize Reporting Statistics 
    total_input_frames = len(buffer.entries)
    total_input_images = 0
    frames_with_output = set()
    images_with_output = set()

    print("\nStarting data processing...")
    # Iterate through each frame (entry) in the buffer using an index for frame_id
    for frame_id, (timestamp, entry) in enumerate(buffer.entries.items()):
        print(f"--- Processing Frame ID: {frame_id} (Timestamp: {timestamp}) ---")

        # Get the robot's odometry for this frame
        odom_to_base = {"position": entry.odometry["position"], "orientation": entry.odometry["orientation"]}

        # Process each synchronized RGB and depth image pair from the five cameras
        for rgb_name, rgb_image, _, depth_image in entry.get_rgb_depth_pairs():
            
            total_input_images += 1
            print(f"  > Processing camera: {rgb_name}")

            # check dimensions match the depth image 
            if rgb_image.shape[:2] != depth_image.shape[:2]:
                rgb_image = cv2.resize(rgb_image, (depth_image.shape[1], depth_image.shape[0]))

            # Generate segmentation masks for the current view 
            masks = mask_generator.generate(rgb_image)
            if not masks:
                print(f"    - No masks generated by SAM for this view.")
                continue
            
            # Calculate the world-to-camera transformation
            w2c = compose_transforms_optimized(
                odom_to_base,
                camera_mapping.get(rgb_name),
                buffer.static_transforms,
                use_optical=True
            )
            pos = w2c["position"]
            orient = w2c["orientation"]
            position_xyz = np.array([pos['x'], pos['y'], pos['z']])
            quaternion_xyzw = np.array([orient['x'], orient['y'], orient['z'], orient['w']])

            # Create individual point clouds for each segmented object
            # returns a list of dictionaries, each containing an Open3D PCD object
            segmented_objects = create_segmented_point_cloud(
                masks, depth_image, rgb_image, position_xyz, quaternion_xyzw
            )
            print(f"    - Found {len(segmented_objects)} objects in this view.")

            # Format and store the data for each object found
            for obj_data in segmented_objects:
                obj_pcd = obj_data['pcd']
                
                # Convert the Open3D point cloud to a NumPy array for serialization
                points_np = np.asarray(obj_pcd.points)
                
                output_dict = {
                    "frame_id": frame_id,
                    "camera_id": rgb_name,
                    "obj_point_cloud": points_np
                }
                all_objects_data.append(output_dict)

                frames_with_output.add(frame_id)
                images_with_output.add((frame_id, rgb_name))

    # 3) Save Results
    print("\nProcessing complete.")

    print("--- 📊 Processing Summary ---")
    print("\n[Input Data]")
    print(f"  - Total Frames in Original Data: {total_input_frames}")
    print(f"  - Total Images (Views) Processed: {total_input_images}")
    print("\n[Output Data]")
    print(f"  - Frames Containing Objects: {len(frames_with_output)}")
    print(f"  - Images Containing Objects: {len(images_with_output)}")
    print(f"  - Total Object Point Clouds Stored: {len(all_objects_data)}")

    if not os.path.exists(OUTPUT_DIR):
        os.makedirs(OUTPUT_DIR)
        
    print(f"Saving {len(all_objects_data)} total object point clouds to {OUTPUT_PATH}...")
    with open(OUTPUT_PATH, "wb") as f:
        pickle.dump(all_objects_data, f)
    print("Successfully saved the data.")


if __name__ == "__main__":
    main()