import pickle
import numpy as np
import torch
import cv2
import open3d as o3d
from segment_anything import sam_model_registry, SamAutomaticMaskGenerator
import os

# Import necessary local modules
from src_perception.obs_data_buffer import ObsDataBuffer, compose_transforms_optimized
from src_perception.components.point_cloud import create_segmented_point_cloud

# CONFIGURATION
# =======================================================
# Path to the pre-trained Segment Anything Model (SAM) checkpoint
SAM_CHECKPOINT_PATH = "models/sam_vit_l_0b3195.pth"
# Path to the serialized observation data buffer
BUFFER_PATH = "data/obs_buffer.pkl" #test_data/sample_obs_buffer_skiped_pattern.pkl"
# Main directory for saving output files
OUTPUT_DIR = "data"
# Directory specifically for saving the generated mask visualization images
MASKS_OUTPUT_DIR = "data/masks_pcds"
# Filename for the final pickled data containing point clouds and mask paths
OUTPUT_FILENAME = "object_pcds.pkl"
# Full path for the final output file
OUTPUT_PATH = os.path.join(OUTPUT_DIR, OUTPUT_FILENAME)
# =======================================================

def main():
    """
    Main function to process observation data, generate segmented object
    point clouds using SAM, and save the results along with visualization images.
    """
    # --- 1) Initialization ---
    print("Initializing script...")
    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    print(f"Using device: {device}")

    print(f"Loading data buffer from: {BUFFER_PATH}")
    if not os.path.exists(BUFFER_PATH):
        print(f"Error: Data buffer not found at {BUFFER_PATH}")
        return
    with open(BUFFER_PATH, "rb") as f:
        buffer: ObsDataBuffer = pickle.load(f)
    print("Data buffer loaded successfully.")

    print(f"Loading SAM model from: {SAM_CHECKPOINT_PATH}")
    if not os.path.exists(SAM_CHECKPOINT_PATH):
        print(f"Error: SAM checkpoint not found at {SAM_CHECKPOINT_PATH}")
        return
    sam = sam_model_registry["vit_l"](checkpoint=SAM_CHECKPOINT_PATH)
    sam.to(device)
    mask_generator = SamAutomaticMaskGenerator(model=sam, min_mask_region_area=1000)
    print("SAM model initialized.")

    # --- 2) Data Processing ---
    all_objects_data = []
    
    camera_mapping = {
        "head_rgb_left": "head_left_rgbd",
        "head_rgb_right": "head_right_rgbd",
        "left_rgb": "left_rgbd",
        "right_rgb": "right_rgbd",
        "rear_rgb": "rear_rgbd"
    }

    # Initialize statistics for the final report
    total_input_frames = len(buffer.entries)
    total_input_images = 0
    total_masks_saved = 0  # NEW: Counter for saved masks
    frames_with_output = set()
    images_with_output = set()

    print("\nStarting data processing...")
    for frame_id, (timestamp, entry) in enumerate(buffer.entries.items()):
        print(f"--- Processing Frame ID: {frame_id} (Timestamp: {timestamp}) ---")

        odom_to_base = {"position": entry.odometry["position"], "orientation": entry.odometry["orientation"]}

        for rgb_name, rgb_image, _, depth_image in entry.get_rgb_depth_pairs():
            total_input_images += 1
            print(f"  > Processing camera: {rgb_name}")

            if rgb_image.shape[:2] != depth_image.shape[:2]:
                rgb_image = cv2.resize(rgb_image, (depth_image.shape[1], depth_image.shape[0]))

            masks = mask_generator.generate(rgb_image)
            if not masks:
                print(f"    - No masks generated by SAM for this view.")
                continue
            
            w2c = compose_transforms_optimized(
                odom_to_base, camera_mapping.get(rgb_name), buffer.static_transforms, use_optical=True
            )
            pos = w2c["position"]
            orient = w2c["orientation"]
            position_xyz = np.array([pos['x'], pos['y'], pos['z']])
            quaternion_xyzw = np.array([orient['x'], orient['y'], orient['z'], orient['w']])

            segmented_objects = create_segmented_point_cloud(
                masks, depth_image, rgb_image, position_xyz, quaternion_xyzw
            )
            print(f"    - Found {len(segmented_objects)} objects in this view.")

            for obj_idx, obj_data in enumerate(segmented_objects):
                mask_info = masks[obj_idx]
                mask_boolean = mask_info['segmentation']
                bbox = mask_info['bbox']

                viz_image = rgb_image.copy()

                color = np.random.randint(0, 256, size=3, dtype=np.uint8)
                color_overlay = np.zeros_like(viz_image, dtype=np.uint8)
                color_overlay[mask_boolean] = color

                viz_image = cv2.addWeighted(viz_image, 0.6, color_overlay, 0.4, 0)

                x, y, w, h = bbox
                box_color = (int(color[0]), int(color[1]), int(color[2]))
                pt1 = (int(x), int(y))
                pt2 = (int(x + w), int(y + h))
                cv2.rectangle(viz_image, pt1, pt2, box_color, 2)

                mask_filename = f"frame_{frame_id}_cam_{rgb_name}_obj_{obj_idx}.png"
                mask_filepath = os.path.join(MASKS_OUTPUT_DIR, mask_filename)
                
                # --- MODIFICATION: Check if image saving was successful ---
                try:
                    success = cv2.imwrite(mask_filepath, viz_image)
                    if success:
                        total_masks_saved += 1
                    else:
                        # Add a warning if the file was not written for any reason
                        print(f"    - WARNING: Failed to save mask image to {mask_filepath}")
                except Exception as e:
                    print(f"    - ERROR: An exception occurred while saving mask to {mask_filepath}: {e}")

                obj_pcd = obj_data['pcd']
                points_np = np.asarray(obj_pcd.points)
                
                output_dict = {
                    "frame_id": frame_id,
                    "camera_id": rgb_name,
                    "obj_point_cloud": points_np,
                    "mask_path": mask_filepath
                }
                all_objects_data.append(output_dict)

                frames_with_output.add(frame_id)
                images_with_output.add((frame_id, rgb_name))

    # --- 3) Save Results & Final Report ---
    print("\nProcessing complete.")
    print("--- 📊 Processing Summary ---")
    print("\n[Input Data]")
    print(f"  - Total Frames in Original Data: {total_input_frames}")
    print(f"  - Total Images (Views) Processed: {total_input_images}")
    print("\n[Output Data]")
    print(f"  - Frames Containing Objects: {len(frames_with_output)}")
    print(f"  - Images Containing Objects: {len(images_with_output)}")
    print(f"  - Total Object Point Clouds Stored: {len(all_objects_data)}")
    # NEW: Report the number of masks successfully saved
    print(f"  - Total Mask Images Saved: {total_masks_saved}")

    # Ensure the output directories exist before saving files
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    os.makedirs(MASKS_OUTPUT_DIR, exist_ok=True)
        
    print(f"\nSaving {len(all_objects_data)} total object data entries to {OUTPUT_PATH}...")
    with open(OUTPUT_PATH, "wb") as f:
        pickle.dump(all_objects_data, f)
    print("Successfully saved the data.")


if __name__ == "__main__":
    main()