import numpy as np
import open3d as o3d
from scipy.spatial.transform import Rotation as R
import torch
import time
from typing import List


#new method:
def generate_distinct_colors(n):
    """Generates n visually distinct colors."""
    colors = []
    for i in range(n):
        # These values are chosen to create a good spread across the color spectrum
        hue = i * 0.61803398875  # Golden ratio ensures good separation
        hue %= 1
        # Simple HSV to RGB conversion
        if hue < 1/6.:
            r, g, b = 1, hue*6, 0
        elif hue < 2/6.:
            r, g, b = 1-(hue-1/6.)*6, 1, 0
        elif hue < 3/6.:
            r, g, b = 0, 1, (hue-2/6.)*6
        elif hue < 4/6.:
            r, g, b = 0, 1-(hue-3/6.)*6, 1
        elif hue < 5/6.:
            r, g, b = (hue-4/6.)*6, 0, 1
        else:
            r, g, b = 1, 0, 1-(hue-5/6.)*6
        
        colors.append((int(r*255), int(g*255), int(b*255)))
    return colors
# hard-coded filtering inside func:
def create_segmented_point_cloud(masks, depth_image, rgb_image, position, quaternion_xyzw):
    """
    Creates a 3D point cloud where points are pre-colored by their mask ID.
    
    Returns:
        A list of Open3D PointCloud objects, one for each input mask.
    """
    H, W = depth_image.shape
    
    # 1) "Color Mask" Image 
    color_mask_image = np.zeros((H, W, 3), dtype=np.uint8) # a blank image
    
    distinct_colors = generate_distinct_colors(len(masks)) # get unique colors for each mask

    for i, mask in enumerate(masks):
        color_mask_image[mask['segmentation']] = distinct_colors[i] # paint each mask area onto the blank img

    # 2) Create a single point cloud using the "Color Mask" 
    full_pcd, _ = depth_to_pointcloud(      # call depth_to_pointcloud w generated color_mask_image
        depth=depth_image,
        rgb=color_mask_image,  
        position=position,
        quaternion_xyzw=quaternion_xyzw
    )

    # 2.1) filtering: ceiling and floor
    points = np.asarray(full_pcd.points)
    filtering = (points[:,2] < 20) & (points[:,2] > 0.1)
    indices2keep = np.where(filtering)[0]
    full_pcd = full_pcd.select_by_index(indices2keep)


    # 3) Extract individual objects by color
    if not full_pcd.has_points(): #check
        return []

    # Get all points and their colors from the full point cloud
    points = np.asarray(full_pcd.points)
    colors = (np.asarray(full_pcd.colors) * 255).astype(np.uint8)

    object_pcds = []
    for color in distinct_colors:
        # Find all points that match the current unique color
        target_color = np.array(color)
        indices = np.where(np.all(colors == target_color, axis=1))[0]

        if len(indices) > 0:
            object_points = points[indices] #selet points for this obj

            # Create a new obj point cloud for this obj
            obj_pcd = o3d.geometry.PointCloud() 
            obj_pcd.points = o3d.utility.Vector3dVector(object_points)
            
            # Give it the original color for visualization
            obj_pcd.paint_uniform_color([c/255.0 for c in color])

            object_pcds.append(obj_pcd)

    return object_pcds


# old method, manual calculations
def get_o3d_cam_intrinsic(height, width):
    """Returns the Open3D camera intrinsic object based on image size."""
    fx = width / 2.0
    fy = width / 2.0
    cx = width / 2.0
    cy = height / 2.0
    return o3d.camera.PinholeCameraIntrinsic(width, height, fx, fy, cx, cy)
# instead of using o3d.geometry.PointCloud.create_from_rgbd_image (depth_to_pointcloud in obs_data_buffer.py)
# I used the raw mathmatical calculation using np to have more direct control over process.
# I want to directly use the 2D mask generated by SAM to select coresponding 3D points.
# so it retains the 2D strucutre of original image and i can use 2D mask to select the points from list. (not happened int Open3D high-level func bc of filtering)
def get_organized_point_cloud(depth_np, camera_pose_7d, camera_intrinsics):  
    """Projects a depth image into a 3D point cloud in world coordinates."""
    H, W = depth_np.shape
    fx, fy, cx, cy = camera_intrinsics.intrinsic_matrix[0, 0], camera_intrinsics.intrinsic_matrix[1, 1], camera_intrinsics.intrinsic_matrix[0, 2], camera_intrinsics.intrinsic_matrix[1, 2]
    
    u, v = np.meshgrid(np.arange(W), np.arange(H))
    Z_cam = depth_np
    X_cam = (u - cx) * Z_cam / fx
    Y_cam = (v - cy) * Z_cam / fy
    points_camera_frame = np.stack([X_cam, Y_cam, Z_cam], axis=-1) # (-1) for creae the new last dimention
    
    points_flat = points_camera_frame.reshape(-1, 3) #grid to simple list of points for matrix multiplication \ (H, W, 3) to (H*W, 3)
    quat_wxyz, position_xyz = camera_pose_7d[:4], camera_pose_7d[4:]
    rotation_matrix = R.from_quat(quat_wxyz[[1, 2, 3, 0]]).as_matrix() # w,x,y,z -> x,y,z,w
    
    c2w_transform = np.eye(4) #identity matrix (4x4) to place info for both rotate and move points from camera fram to world frame
    c2w_transform[:3, :3] = rotation_matrix #placed in the top-left corner
    c2w_transform[:3, 3] = position_xyz #placed in the last column

    points_homogeneous = np.hstack((points_flat, np.ones((points_flat.shape[0], 1)))) #add 4th component to every point in the flattened list #(N, 4)
    #c2w_transform
    # [R, R, R, | T]        R rotaion matrix
    # [R, R, R, | T]        T translation vector X Y Z
    # [R, R, R, | T]
    # [0, 0, 0, | 1]     - points_homogeneous (trick)
    points_world_homogeneous = (c2w_transform @ points_homogeneous.T).T #transformation:matrix multipication. result (N,4) 
    
    return points_world_homogeneous[:, :3].reshape(H, W, 3) #select only x,y,z values (w discarding) #reshape to match input image





